baseURL = "https://gulsevenyagiz.com"
canonifyURLs = true
languageCode = "en-us"
title = "Documentation"
theme = "hugo-theme-learn"




[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
