# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build hugo
        run: |
          sudo apt-get install -y hugo
          pwd
          ls -la
          hugo new site yagiz
          ls -la
          mv -f /home/runner/work/documentation/documentation/content/ /home/runner/work/documentation/documentation/yagiz/
          ls -la /home/runner/work/documentation/documentation/yagiz/content/
          git clone https://github.com/matcornic/hugo-theme-learn.git /home/runner/work/documentation/documentation/yagiz/themes/hugo-theme-learn
          mv -f /home/runner/work/documentation/documentation/config.toml /home/runner/work/documentation/documentation/yagiz/

      - name: Run Hugo
        working-directory: ./yagiz
        run: hugo                 
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: /home/runner/work/documentation/documentation/yagiz/public
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

      - name: Run the deployment script.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT  }}
          script: sudo ~/deploy.sh